import * as pulumi from '@pulumi/pulumi';
import * as aws from '@pulumi/aws';

const config = new pulumi.Config();
const REGION: any = config.require('aws_region');
const lsEndpoint = "http://localhost:4566"

export class PulumiUtil {
    static awsProvider: any;
    static env: string;
}


PulumiUtil.awsProvider = new aws.Provider("localstack", {
    skipCredentialsValidation: true,
    skipMetadataApiCheck: true,
    skipRequestingAccountId: true,
    // s3ForcePathStyle: true,
    accessKey: "test",
    secretKey: "test",
    region: REGION,
    // list of supported features
    // https://docs.localstack.cloud/aws/feature-coverage/
    // list of feature status
    // https://app.localstack.cloud/status
    endpoints: [{
        accessanalyzer: `${lsEndpoint}`,
        account: `${lsEndpoint}`,
        acm: `${lsEndpoint}`,
        acmpca: `${lsEndpoint}`,
        amp: `${lsEndpoint}`,
        amplify: `${lsEndpoint}`,
        apigateway: `${lsEndpoint}`,
        apigatewayv2: `${lsEndpoint}`,
        appautoscaling: `${lsEndpoint}`,
        appconfig: `${lsEndpoint}`,
        appflow: `${lsEndpoint}`,
        appintegrations: `${lsEndpoint}`,
        appintegrationsservice: `${lsEndpoint}`,
        applicationautoscaling: `${lsEndpoint}`,
        applicationinsights: `${lsEndpoint}`,
        appmesh: `${lsEndpoint}`,
        apprunner: `${lsEndpoint}`,
        appstream: `${lsEndpoint}`,
        appsync: `${lsEndpoint}`,
        athena: `${lsEndpoint}`,
        auditmanager: `${lsEndpoint}`,
        autoscaling: `${lsEndpoint}`,
        autoscalingplans: `${lsEndpoint}`,
        backup: `${lsEndpoint}`,
        batch: `${lsEndpoint}`,
        budgets: `${lsEndpoint}`,
        chime: `${lsEndpoint}`,
        cloud9: `${lsEndpoint}`,
        cloudcontrol: `${lsEndpoint}`,
        cloudcontrolapi: `${lsEndpoint}`,
        cloudformation: `${lsEndpoint}`,
        cloudfront: `${lsEndpoint}`,
        cloudhsm: `${lsEndpoint}`,
        cloudhsmv2: `${lsEndpoint}`,
        cloudsearch: `${lsEndpoint}`,
        cloudtrail: `${lsEndpoint}`,
        cloudwatch: `${lsEndpoint}`,
        cloudwatchevents: `${lsEndpoint}`,
        cloudwatchlogs: `${lsEndpoint}`,
        codeartifact: `${lsEndpoint}`,
        codebuild: `${lsEndpoint}`,
        codecommit: `${lsEndpoint}`,
        codedeploy: `${lsEndpoint}`,
        codegurureviewer: `${lsEndpoint}`,
        codepipeline: `${lsEndpoint}`,
        codestarconnections: `${lsEndpoint}`,
        codestarnotifications: `${lsEndpoint}`,
        cognitoidentity: `${lsEndpoint}`,
        cognitoidentityprovider: `${lsEndpoint}`,
        cognitoidp: `${lsEndpoint}`,
        comprehend: `${lsEndpoint}`,
        config: `${lsEndpoint}`,
        configservice: `${lsEndpoint}`,
        connect: `${lsEndpoint}`,
        costandusagereportservice: `${lsEndpoint}`,
        costexplorer: `${lsEndpoint}`,
        cur: `${lsEndpoint}`,
        databasemigration: `${lsEndpoint}`,
        databasemigrationservice: `${lsEndpoint}`,
        dataexchange: `${lsEndpoint}`,
        datapipeline: `${lsEndpoint}`,
        datasync: `${lsEndpoint}`,
        dax: `${lsEndpoint}`,
        detective: `${lsEndpoint}`,
        devicefarm: `${lsEndpoint}`,
        directconnect: `${lsEndpoint}`,
        dlm: `${lsEndpoint}`,
        dms: `${lsEndpoint}`,
        docdb: `${lsEndpoint}`,
        ds: `${lsEndpoint}`,
        dynamodb: `${lsEndpoint}`,
        ec2: `${lsEndpoint}`,
        ecr: `${lsEndpoint}`,
        ecrpublic: `${lsEndpoint}`,
        ecs: `${lsEndpoint}`,
        efs: `${lsEndpoint}`,
        eks: `${lsEndpoint}`,
        elasticache: `${lsEndpoint}`,
        elasticbeanstalk: `${lsEndpoint}`,
        elasticsearch: `${lsEndpoint}`,
        elasticsearchservice: `${lsEndpoint}`,
        elastictranscoder: `${lsEndpoint}`,
        elb: `${lsEndpoint}`,
        elbv2: `${lsEndpoint}`,
        emr: `${lsEndpoint}`,
        emrcontainers: `${lsEndpoint}`,
        es: `${lsEndpoint}`,
        eventbridge: `${lsEndpoint}`,
        events: `${lsEndpoint}`,
        finspace: `${lsEndpoint}`,
        firehose: `${lsEndpoint}`,
        fis: `${lsEndpoint}`,
        fms: `${lsEndpoint}`,
        fsx: `${lsEndpoint}`,
        gamelift: `${lsEndpoint}`,
        glacier: `${lsEndpoint}`,
        globalaccelerator: `${lsEndpoint}`,
        glue: `${lsEndpoint}`,
        greengrass: `${lsEndpoint}`,
        guardduty: `${lsEndpoint}`,
        healthlake: `${lsEndpoint}`,
        iam: `${lsEndpoint}`,
        identitystore: `${lsEndpoint}`,
        imagebuilder: `${lsEndpoint}`,
        inspector: `${lsEndpoint}`,
        iot: `${lsEndpoint}`,
        iotanalytics: `${lsEndpoint}`,
        iotevents: `${lsEndpoint}`,
        kafka: `${lsEndpoint}`,
        kafkaconnect: `${lsEndpoint}`,
        kendra: `${lsEndpoint}`,
        kinesis: `${lsEndpoint}`,
        kinesisanalytics: `${lsEndpoint}`,
        kinesisanalyticsv2: `${lsEndpoint}`,
        kinesisvideo: `${lsEndpoint}`,
        kms: `${lsEndpoint}`,
        lakeformation: `${lsEndpoint}`,
        lambda: `${lsEndpoint}`,
        lexmodelbuilding: `${lsEndpoint}`,
        lexmodelbuildingservice: `${lsEndpoint}`,
        lexmodels: `${lsEndpoint}`,
        lexmodelsv2: `${lsEndpoint}`,
        licensemanager: `${lsEndpoint}`,
        lightsail: `${lsEndpoint}`,
        location: `${lsEndpoint}`,
        macie2: `${lsEndpoint}`,
        mediaconnect: `${lsEndpoint}`,
        mediaconvert: `${lsEndpoint}`,
        medialive: `${lsEndpoint}`,
        mediapackage: `${lsEndpoint}`,
        mediastore: `${lsEndpoint}`,
        memorydb: `${lsEndpoint}`,
        mq: `${lsEndpoint}`,
        mwaa: `${lsEndpoint}`,
        neptune: `${lsEndpoint}`,
        networkfirewall: `${lsEndpoint}`,
        networkmanager: `${lsEndpoint}`,
        opsworks: `${lsEndpoint}`,
        organizations: `${lsEndpoint}`,
        outposts: `${lsEndpoint}`,
        pinpoint: `${lsEndpoint}`,
        pricing: `${lsEndpoint}`,
        prometheus: `${lsEndpoint}`,
        prometheusservice: `${lsEndpoint}`,
        qldb: `${lsEndpoint}`,
        quicksight: `${lsEndpoint}`,
        ram: `${lsEndpoint}`,
        rds: `${lsEndpoint}`,
        redshift: `${lsEndpoint}`,
        redshiftdata: `${lsEndpoint}`,
        resourcegroups: `${lsEndpoint}`,
        resourcegroupstagging: `${lsEndpoint}`,
        resourcegroupstaggingapi: `${lsEndpoint}`,
        route53: `${lsEndpoint}`,
        route53domains: `${lsEndpoint}`,
        route53recoverycontrolconfig: `${lsEndpoint}`,
        route53recoveryreadiness: `${lsEndpoint}`,
        route53resolver: `${lsEndpoint}`,
        s3: `${lsEndpoint}`,
        s3control: `${lsEndpoint}`,
        s3outposts: `${lsEndpoint}`,
        sagemaker: `${lsEndpoint}`,
        schemas: `${lsEndpoint}`,
        sdb: `${lsEndpoint}`,
        secretsmanager: `${lsEndpoint}`,
        securityhub: `${lsEndpoint}`,
        serverlessapplicationrepository: `${lsEndpoint}`,
        serverlessapprepo: `${lsEndpoint}`,
        serverlessrepo: `${lsEndpoint}`,
        servicecatalog: `${lsEndpoint}`,
        servicediscovery: `${lsEndpoint}`,
        servicequotas: `${lsEndpoint}`,
        ses: `${lsEndpoint}`,
        sesv2: `${lsEndpoint}`,
        sfn: `${lsEndpoint}`,
        shield: `${lsEndpoint}`,
        signer: `${lsEndpoint}`,
        simpledb: `${lsEndpoint}`,
        sns: `${lsEndpoint}`,
        sqs: `${lsEndpoint}`,
        ssm: `${lsEndpoint}`,
        ssmcontacts: `${lsEndpoint}`,
        ssmincidents: `${lsEndpoint}`,
        ssoadmin: `${lsEndpoint}`,
        stepfunctions: `${lsEndpoint}`,
        storagegateway: `${lsEndpoint}`,
        sts: `${lsEndpoint}`,
        swf: `${lsEndpoint}`,
        synthetics: `${lsEndpoint}`,
        timestreamwrite: `${lsEndpoint}`,
        transcribe: `${lsEndpoint}`,
        transcribeservice: `${lsEndpoint}`,
        transfer: `${lsEndpoint}`,
        waf: `${lsEndpoint}`,
        wafregional: `${lsEndpoint}`,
        wafv2: `${lsEndpoint}`,
        worklink: `${lsEndpoint}`,
        workspaces: `${lsEndpoint}`,
        xray: `${lsEndpoint}`
    }],
})


let stackPieces: string[] = pulumi.getStack().split('.');
PulumiUtil.env = stackPieces[stackPieces.length - 1];
